### ISSUE TITLE
[Blessing of Autumn] Paladin - 328622

### ISSUE THREAD

**Issue by Belebacsi** [AshamaneProject/BugTracker#14]
**Spell**
https://www.wowhead.com/spell=328622/blessing-of-autumn

**Class & Specialization**
Paladin - holy

**Describe the bug**
Blessing of Autumn doesn't turn into Blessing of winter on use

**To Reproduce**
Steps to reproduce the behavior. Example :
1. Cast spell
2. See it doesn't cycle to Blessing of Winter

**Expected behavior**
Supposed to cycle through all blessings of spells

**Criticality**
 [ ] High : This bug has a major impact on the spec dps/hps/survivability

**Comment by Traesh** [comment]
Fixed
