### ISSUE TITLE
[Shadow Dance] rogue 185313

### ISSUE THREAD

**Issue by bratkox** [AshamaneProject/BugTracker#15]
<-- ANY INCOMPLETE ISSUE WILL BE AUTOMATICALY CLOSED. DELETE THIS LINE BEFORE SENDING -->

**Spell**
[A wowhead link to the affected spell.](https://www.wowhead.com/spell=185313/shadow-dance)

**Class & Specialization**
subtlety rogue

**Describe the bug**
I have this spell even tho i dont have it talented.

**Expected behavior**
I should not have it after i retalent and dont have it talented.

**Criticality**
 [ ] Breaking class

**Screenshots/Videos (Optional)**
![haha](https://github.com/AshamaneProject/BugTracker/assets/129157583/6b2b7c2a-7727-460a-bc83-a51fc3c39e00)

**Comment by Traesh** [comment]
As stated in the talent, some spec already have Shadow Dance by default. If you already know Shadow Dance, this talent just add another charge to the spell.
