### ISSUE TITLE
[Spell] Mage - 314791 - Shifting-Power

### ISSUE THREAD

**Issue by zaralock** [AshamaneProject/BugTracker#17]
Spell
Shifting Power
https://www.wowhead.com/spell=314791/shifting-power

Class/Specialization
Fire Mage
Talents: https://imgur.com/a/02yJWwb

Describe the bug
Shifting Power: While channeling, your Mage ability cooldowns are reduced by 12 sec over 3.6 sec wich is not working at all

Criticality
Breaking Class: Should be a big issuse dps wise after you used all of your cds

Screenshots/Videos (Optional)
Video: https://imgur.com/a/pFbgtG0

**Comment by Traesh** [comment]
Fixed on next reboot
