### ISSUE TITLE
Paladin consecrtion not working

### ISSUE THREAD

**Issue by TheVaiil** [AshamaneProject/BugTracker#2]
The consecration spell does not do any damage within the area where mobs are, it lands on the ground fine but with no damage.

https://github.com/AshamaneProject/BugTracker/assets/3145666/b7b973ee-3544-477a-a48a-60bdcb608f4c

**Comment by Traesh** [comment]
Hello, i can't reproduce on my side, do you have any talent that may affect the consecration ?

https://i.imgur.com/KeEoet2.png

**Comment by TheVaiil** [comment]
So checking again on a new char, it might be my main char that i used in the video that maybe was bugged or the mobs near valdrakken that did not work xD
