### ISSUE TITLE
[Cleanse] Paladin - 4987

### ISSUE THREAD

**Issue by Belebacsi** [AshamaneProject/BugTracker#21]
**Spell**
https://www.wowhead.com/spell=4987/cleanse

**Class & Specialization**
Paladin - Holy

**Describe the bug**
Cleanse doesn't remove Poison

**To Reproduce**
1. Get Poison on yourself
2. Use Cleanse

**Expected behavior**
Cleanse is supposed to remove Poison

**Criticality**
 [ ] Medium : End content is doable but harder than is should (20% less damage, ...)

**Comment by Traesh** [comment]
Related to https://www.wowhead.com/spell=393024/improved-cleanse

Fixed on next reboot
