### ISSUE TITLE
[Spell] Fire Mage - 155148 - Kindling

### ISSUE THREAD

**Issue by zaralock** [AshamaneProject/BugTracker#24]
Spell
Combustion
https://www.wowhead.com/spell=155148/kindling

Class/Specialization
Fire Mage
Talents: https://imgur.com/a/02yJWwb

Describe the bug
Kindling: Your Fireball, Pyroblast, Fire Blast, Scorch and Phoenix Flames critical strikes reduce the remaining cooldown on Combustion by 1.0 sec, wich is working a bit more overpowered that it should be your critical strikes are reseting the whole cooldown on combustion

Criticality
Breaking Class: What can i say haha

Video: https://imgur.com/hNMkwlB

**Comment by Traesh** [comment]
Fixed on next reboot
