### ISSUE TITLE
[Spell] Fire Mage - 383886 - Sun King's Blessing

### ISSUE THREAD

**Issue by zaralock** [AshamaneProject/BugTracker#34]
Spell
Sun King's Blessing		
https://www.wowhead.com/spell=383886/sun-kings-blessing

Class/Specialization
Fire Mage

Describe the bug
After consuming 8 hot streaks, your non-instant pyroblast or flamestrike cast within 30sec grants your combustion for 6 sec and deals 260% additional damage not working at all

Criticality
Breaking Class: Can be a huge dps loss bot Single Target/AoE fights

Video: im not posting but the talent is not working even if you consume more that 8 hot streak

**Comment by Traesh** [comment]
Fixed on next reboot
