### ISSUE TITLE
Divine Toll

### ISSUE THREAD

**Issue by TheVaiil** [AshamaneProject/BugTracker#4]
Divine toll does not deal damage, it only applies  the Divine resonance buff

https://github.com/AshamaneProject/BugTracker/assets/3145666/4ec826da-b881-4523-9b9b-ce7b49a4fb51

https://www.wowhead.com/spell=304971/divine-toll

**Comment by Traesh** [comment]
@TheVaiil Fixed, including the "Divine resonance" talent

Would need some testing to make sure i properly fixed it :)

Feel free to re-open this ticket if i missed anything
