### ISSUE TITLE
[Summon Voidwalker] Warlock - 697

### ISSUE THREAD

**Issue by Belebacsi** [AshamaneProject/BugTracker#42]
**Spell**
https://www.wowhead.com/spell=697/summon-voidwalker

**Class & Specialization**
Warlock - Destruction

**Describe the bug**
Voidwalker is not spawning

**To Reproduce**
Steps to reproduce the behavior. Example :
1. Cast the spell on '...'
2. Observe that it does '....'
3. See error

**Expected behavior**
Voidwalker should spawn

**Criticality**
 [ ] Breaking class : The class/spec isn't playable without this spell fixed. (Taunt for a tank, Mage's Fireball doing 0 damage, ...)

**Screenshots/Videos (Optional)**
https://imgur.com/a/Flq5ViV

**Comment by Traesh** [comment]
Fixed
