### ISSUE TITLE
[Summon Felhunter] Warlock - 691

### ISSUE THREAD

**Issue by Belebacsi** [AshamaneProject/BugTracker#43]
**Spell**
https://www.wowhead.com/spell=691/summon-felhunter

**Class & Specialization**
Warlock - Destruction

**Describe the bug**
Felhunter is not spawning

**To Reproduce**
Steps to reproduce the behavior. Example :

    Cast the spell on '...'
    Observe that it does '....'
    See error

**Expected behavior**
Felhunter should spawn

**Criticality**
[ ] Breaking class : The class/spec isn't playable without this spell fixed. (Taunt for a tank, Mage's Fireball doing 0 damage, ...)

**Screenshots/Videos (Optional)**
https://imgur.com/a/Flq5ViV

**Comment by Traesh** [comment]
Fixed
