### ISSUE TITLE
[Spell] Fire Mage - 314791 - Shifting-Power

### ISSUE THREAD

**Issue by zaralock** [AshamaneProject/BugTracker#61]
Spell
Shifting Power
https://www.wowhead.com/spell=314791/shifting-power

Class/Specialization
Fire Mage
Talents: https://imgur.com/a/02yJWwb

Describe the bug
Shifting Power: While channeling, your Mage ability cooldowns are reduced by 12 sec over 3.6 sec 
UPDATE its only reducing combustion cooldown should be affect fire blast and phoniex flames also

Criticality
Breaking Class: Should be a big issuse dps wise after you used all of your cds

**Comment by Traesh** [comment]
Fixed
