### ISSUE TITLE
[Spell] Fire Mage - 194466 - Phoniex Flames

### ISSUE THREAD

**Issue by zaralock** [AshamaneProject/BugTracker#7]
Spell
Phoniex Flames 
https://www.wowhead.com/spell=257541/phoenix-flames

Class/Specialization
Fire Mage
Talents: https://imgur.com/a/02yJWwb

Describe the bug
Phoniex Flames should be always a critical strike witch means it should generate hotsreak wich is not working

Criticality
Breaking Class: Flame Strike is a base spell in the Fire Mage Rotation also main spell for procing hotstreak

Screenshots/Videos (Optional)
Video: https://imgur.com/a/M2BORh1

**Comment by Traesh** [comment]
Fixed
